name: Build TabList

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      # ⬇️ NEW: upload the jar produced by the Gradle build
      - uses: actions/upload-artifact@v4
        with:
          name: TabList-5.7.8-SNAPSHOT.jar
          path: |
            TabList-bukkit/build/libs/TabList-*.jar


          ${{ github.workspace }}/bukkit/build/libs/TabList-bukkit*.jar
          ${{ github.workspace }}/bungee/build/libs/TabList-bungee*.jar
